run:
  concurrency: 8
  deadline: 2m
  issues-exit-code: 1
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf: 
        funcs: 
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
    tab-width: 1
  goimports:
    local-prefixes: github.com/subroll/burrow
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - regexpMust
      - wrapperFunc
      - ifElseChain
      - octalLiteral
    settings: 
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 10
  prealloc:
    simple: true
    range-loops: false
    for-loops: true
linters:
  enable:
    - govet
    - golint
    - gocyclo
    - maligned
    - dupl
    - goconst
    - misspell
    - lll
    - goimports
    - gocritic
    - errcheck
    - gofmt
    - unused
    - unparam
    - nakedret
    - prealloc
    - bodyclose
    - deadcode
    - dogsled
    - gosimple
    - ineffassign
    - interfacer
    - scopelint
    - staticcheck
    - structcheck
    - unconvert
    - varcheck
    - whitespace
  disable-all: true
  fast: false
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
